### ISSUE TITLE
How do I make tab a hotkey?

### ISSUE THREAD

**Issue by seize21** [BetaLeaf/MeepoHelper#1]
My ControlGroupTabKey is set to tab in Dota. How do I set it to tab in the script?

**Comment by BetaLeaf** [comment]
What key is ControlGroupTabKey set to in dota?

**Comment by BetaLeaf** [comment]
In your MeepoHelper.ini, under [Dota2Bindings], set ControlGroupTabKey={tab}, and then restart MeepoHelper.
